import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('opportunity-fulfillment.html','utf8');
const toml=fs.readFileSync('netlify.toml','utf8');
const redirects=fs.readFileSync('_redirects','utf8');
for(const label of ['1 · Select Contract','2 · Build Contract DNA','3 · Search Contractor Repository','4 · Create Business Search','5 · Execute Business Discovery','6 · Enrich Selected Contact','7 · Generate Outreach','8 · Send Outreach']) assert.ok(html.includes(label),`missing ${label}`);
assert.ok(html.includes("page_size:'30'"),'30-record queue missing');
assert.ok(html.includes('Previous 30'),'Previous 30 missing');
assert.ok(html.includes('Select Next 30'),'Next 30 missing');
assert.ok(html.includes("queueToken"),'stale request protection missing');
assert.ok(html.includes('/api/owner-analyze-fit-prep'),'owner handoff missing');
assert.ok(html.includes('/api/otf-record-interest'),'interest recorder missing');
assert.ok(toml.includes('to = "/opportunity-fulfillment.html"'),'netlify.toml route is not authoritative main page');
assert.ok(!toml.includes('to = "/opportunity-fulfillment-operator-v2.html"'),'v2 wrapper still active in netlify.toml');
assert.ok(redirects.includes('/opportunity-fulfillment /opportunity-fulfillment.html 200!'),'_redirects route is not main page');
assert.ok(!redirects.includes('operator-v2'),'v2 wrapper still active in _redirects');
assert.ok(fs.existsSync('archive/otf-recovery/opportunity-fulfillment-operator.html'));
assert.ok(fs.existsSync('archive/otf-recovery/opportunity-fulfillment-operator-v2.html'));
console.log('OTF owner command center regression: PASS');
